// <auto-generated />
using System;
using E_lections.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace E_lections.Migrations
{
    [DbContext(typeof(ELectionsDbContext))]
    partial class ELectionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("E_lections.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JMBG");

                    b.Property<string>("Lozinka");

                    b.HasKey("ID");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("E_lections.Models.GlasackiListic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojGlasova");

                    b.Property<int>("IzborId");

                    b.Property<int>("MaxOdabir");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.HasIndex("IzborId");

                    b.ToTable("GlasackiListic");
                });

            modelBuilder.Entity("E_lections.Models.HistorijaGlasanja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OsobaId");

                    b.Property<string>("glasovi");

                    b.HasKey("ID");

                    b.HasIndex("OsobaId");

                    b.ToTable("HistorijaGlasanja");
                });

            modelBuilder.Entity("E_lections.Models.Izbor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KantonOgranicenje")
                        .IsRequired();

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("Pocetak");

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.ToTable("Izbor");
                });

            modelBuilder.Entity("E_lections.Models.Osoba", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojLicneKarte")
                        .IsRequired()
                        .HasMaxLength(9);

                    b.Property<DateTime>("DatumRodjenja");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("EMail");

                    b.Property<string>("Ime")
                        .IsRequired();

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13);

                    b.Property<string>("Kanton");

                    b.Property<string>("Lozinka");

                    b.Property<string>("Prezime")
                        .IsRequired();

                    b.Property<int>("Spol");

                    b.Property<int?>("StrankaId");

                    b.Property<string>("Ulica");

                    b.HasKey("ID");

                    b.HasIndex("StrankaId");

                    b.ToTable("Osoba");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Osoba");
                });

            modelBuilder.Entity("E_lections.Models.Profil", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Opis");

                    b.Property<string>("PutanjaSlike");

                    b.HasKey("ID");

                    b.ToTable("Profil");
                });

            modelBuilder.Entity("E_lections.Models.Statistika", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GlasoviMusko");

                    b.Property<int>("GlasoviNevalidni");

                    b.Property<int>("GlasoviValidni");

                    b.Property<string>("GlasoviZaKanton");

                    b.Property<int>("GlasoviZensko");

                    b.Property<int>("IzborId");

                    b.HasKey("ID");

                    b.HasIndex("IzborId");

                    b.ToTable("Statistika");
                });

            modelBuilder.Entity("E_lections.Models.Stranka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv");

                    b.HasKey("ID");

                    b.ToTable("Stranka");
                });

            modelBuilder.Entity("E_lections.Models.Glasac", b =>
                {
                    b.HasBaseType("E_lections.Models.Osoba");

                    b.ToTable("Glasac");

                    b.HasDiscriminator().HasValue("Glasac");
                });

            modelBuilder.Entity("E_lections.Models.Kandidat", b =>
                {
                    b.HasBaseType("E_lections.Models.Osoba");

                    b.Property<int?>("GlasackiListicId");

                    b.Property<int?>("ProfilId");

                    b.Property<int>("brojGlasova");

                    b.Property<bool>("isSelected");

                    b.HasIndex("GlasackiListicId");

                    b.HasIndex("ProfilId")
                        .IsUnique()
                        .HasFilter("[ProfilId] IS NOT NULL");

                    b.ToTable("Kandidat");

                    b.HasDiscriminator().HasValue("Kandidat");
                });

            modelBuilder.Entity("E_lections.Models.GlasackiListic", b =>
                {
                    b.HasOne("E_lections.Models.Izbor", "Izbor")
                        .WithMany("GlasackiListici")
                        .HasForeignKey("IzborId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("E_lections.Models.HistorijaGlasanja", b =>
                {
                    b.HasOne("E_lections.Models.Osoba", "Osoba")
                        .WithMany()
                        .HasForeignKey("OsobaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("E_lections.Models.Osoba", b =>
                {
                    b.HasOne("E_lections.Models.Stranka", "Stranka")
                        .WithMany("UpisiUStranku")
                        .HasForeignKey("StrankaId");
                });

            modelBuilder.Entity("E_lections.Models.Statistika", b =>
                {
                    b.HasOne("E_lections.Models.Izbor", "Izbor")
                        .WithMany()
                        .HasForeignKey("IzborId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("E_lections.Models.Kandidat", b =>
                {
                    b.HasOne("E_lections.Models.GlasackiListic", "GlasackiListic")
                        .WithMany("Kandidati")
                        .HasForeignKey("GlasackiListicId");

                    b.HasOne("E_lections.Models.Profil", "Profil")
                        .WithOne("Kandidat")
                        .HasForeignKey("E_lections.Models.Kandidat", "ProfilId");
                });
#pragma warning restore 612, 618
        }
    }
}
